# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'textbook-app' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for textbook-app
pod ‘SwiftOCR'
pod ‘SwiftyJSON’
  target 'textbook-appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'textbook-appUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
